### ISSUE TITLE
65pus6703/12 cannot pair[BUG]

### ISSUE THREAD

**Issue by Qbunjo** [eslavnov/pylips#104] opened 2021-02-16 14:29 UTC
When trying to pair TV with pylips I get

IP 192.168.X.X is online, but no known API is found. Exiting...
My TV is 65PUS6703/12 from 2018. It's SAPHI tv. It looks that pylips can't get any reasonable answer from tv.

**Comment by eslavnov** [comment] 2021-02-16 17:12
Hi @Qbunjo,

Please run Pylips with `--verbose True` and share the full output (not just the last line).

**Comment by Qbunjo** [comment] 2021-02-17 11:12
Ok, today the tv responses, but I think something is wrong anyway...

Checking API version and port...
Trying http://192.168.0.X:1925/6/system
Connected to MQTT broker at 192.168.0.YY
Started MQTT status updater
Sending GET request to http://192.168.0.X:1925/6/powerstate
Request sent!
Sending GET request to http://192.168.0.X:1925/6/audio/volume
Request sent!
Sending GET request to http://192.168.0.X:1925/6/activities/current
Request sent!
Sending GET request to http://192.168.0.X:1925/6/ambilight/currentconfiguration
Request sent!
Sending GET request to http://192.168.0.X:1925/6/HueLamp/power
Request sent!

and here it falls into a loop...

**Comment by eslavnov** [comment] 2021-02-17 11:44
The loop is the result of you using `MQTT_update = True` in your settings and is the expected behavior. I suggest disabling MQTT altogether and firing some manual commands (like `--command standby`). Once you figure them out, then you can introduce some extra complexity by adding MQTT to the mix.

I'm closing this one since it seems you were able to pair. Feel free to open a separate issue if you still have problems (after trying it without MQTT).

**Closed as completed by eslavnov** 2021-02-17 11:44 UTC
Labels: bug
