### ISSUE TITLE
[BUG] Cannot control Ambilight on 55oled855/12

### ISSUE THREAD

**Issue by losdrugi** [eslavnov/pylips#90] opened 2021-01-08 16:17 UTC
Hello, 

Many, many thanks for your excellent work and all the effort you took on reverse engineering!

I just tried to run Ambilight commands from the script. On and Off commands work perfectly, but I cannot control color parameters, although the API returns OK status: 

Here are some example calls, with no effect on TV: 

$python3 pylips.py --command ambilight_color --body '{"hue": 200, "saturation": 10, "brightness": 100}'
Sending POST request to https://192.168.1.23:1926/6/ambilight/currentconfiguration
Request sent!
{"response": "OK"}

$python3 pylips.py --command ambilight_brightness --body '{"value":10}'
Sending POST request to https://192.168.1.23:1926/6/menuitems/settings/update
Request sent!
{"response": "OK"}

I have 55oled855/12 with the firmware TPM191E_R.101.001.123.009

I was also trying to install Home Assistant HACS addon to automate Ambilights, but also with no success, so I guess soemthing was changed in API recently... :-/ 

Kind Regards, 
Marcin

**Comment by eslavnov** [comment] 2021-01-15 12:54
Hi @losdrugi,

The TV sends the correct response, so I am afraid it's indeed some kind of an API change or something else on the TV's side. Have you tried using the official Philips TV remote mobile app? If it also does not work, then unfortunately there is nothing I can do. If it works, we can investigate it together and add a proper support for your particular model.

**Comment by eslavnov** [comment] 2021-02-14 11:04
Closing since I can't reproduce this and I don't have enough info to investigate.

**Closed by eslavnov** 2021-02-14 11:04 UTC
Labels: question
